# Generated by Django 6.0.3 on 2026-03-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_registroponto_latitude_registroponto_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='atrasado',
            field=models.BooleanField(default=False),
        ),
    ]
